---
title: "article"
format: html
editor: visual
---

## Nationalism Final Exam

The Battle of Algiers is a movie that shows actions taken by rebel forces in Algiera to fight off French colonialism in North Africa. Throughout the film, different themes appear, such as community, equality and increased warfare. These themes relate to several theories we have discussed throughout the year. Anderson Benedict's theories help explain the Algerians' imagined communities, Adria Lawrence explains how nationalism is created from a fight for equality, Barry Posen discusses how one must imitate warfare so their nation does not perish and the idea of ranked and unranked systems. 

One major theme present is the idea of a community. This relates to Benedict Anderson's ideas on an imagined community and how that builds nationalism. One example he provides when explaining this theory is the idea of a religious pilgrimage. He says that although people didn't speak the same language, were illiterate or didn't see the land they were traveling to as sacred, what brought them together was their religion and, "Journey between times, statuses, and places, as a meaning-creating experience." We see in the film that not everyone is literate when Ali asks the young boy to read him a note. The Algerian people are connected by their religion yet they are also connected by the shared experience they have. For the past 130 years, as claimed by one of the liberation leaders in the movie, they have been oppressed and ruled by the French. This shared experience brings them together and causes them to become nationalistic toward their imagined community. Prisoners chant to each other, "Long live Algeria," and broadcasters claim to the public that they must fight for the independence of their nation. You can also see their connection to their community during the end of the movie, when there is a large protest. They begin waving sheets and blankets as flags, but they don't care what the flag looks like, they are purely waving it to show their allegiance to their nation. This relates to the course because before I would have assumed that they were a part of this movement purely because they were Algerian. I wouldn't have been able to recognize the connection they have with one another based on history and religion. Now with my knowledge of Benedict's theories, I can recognize the imagined community that the Algerian people have created. 

A theme of equality and unequal treatment is shown throughout many of the scenes in the movie. This resonates with Adria Lawrence's theories and ideas on nationalism relating to imperial rule. She discusses in the introduction of her book how the Algerian fight for independence was due to unequal treatment by the government. We see this unequal treatment in several ways: When Ali is tripped by the group of what I presume are French men and then followed by them after his arrest, how the elder Algerian man is berated and beaten by schoolboys who call him names, and how an Algerian man is calmly sitting on the curb and is harassed by the residents and called a "murderer" and "Dirty Arab." It also relates to her idea of disillusionment. She claims that in places where the French did not extend equality, movements geared towards equal rights turned into nationalist movements. She also says that nationalism becomes political after attempts at seeking equality fail.  We see this in the film with the broadcasts. They no longer ask for equal rights, but instead they ask for independence for Algeria.  Before this class, I would not have recognized the connection to Lawrence's ideas about equal rights efforts morphing into a nationalist movement. I would have just seen the unequal treatment and assumed the violence and efforts to stop the French army were due to those actions and not due to the nationalist movement they had formed from this lack of equality. 

We see a theme of increased violence as well throughout the movie. As the fight for independence grows stronger, the violence between the French and Algerians increases. This relates to when we learned about Posen's theory of warfare and imitation. Posen believed that as nationalism increases, so does warfare. This is true for the Algerians. As their cause grows they become more violent with the French. This also relates to his idea of imitation. Posen says that if a nation does not increase their military capabilities, they will eventually perish. The Algerians are oppressed by the strong French military and in an attempt to stop their community from perishing, they begin to imitate the cruel warfare that the French have been using on them for decades. Just as the police will mistreat random Algerians, they begin to mistreat random police in the name of their fight for independence. As the movie progresses, we see Algerians being tortured through methods such as electric shocks or being hanged from wooden planks. This also contributes to their increased violence because Algerians begin to see their community perish, and realize they need to use the same retaliatory force in order to keep their community alive. This course has affected my view on the movie because I would have previously thought they were just angry and therefore, resorting to violence. But due to our exploration of Posen's theories, I now see how nationalism has played a role in the violence enacted by the Algerians on the French and how imitation plays a role in the actions they take. 

The movie also related to the themes of superior and inferior groups. This reminded me of the lessons where we covered the topic pertaining to ranked and unranked groups. It seemed like at this point in time in Algiers, they had ranked and unranked groups. The Algerians were clearly below the French and this was present by the way they were treated, not just by the government and military, but also by the French residents who resided there. Before this class, I would not have recognized the unranked system that was present between the Algerians and the French. I would have just recognized it as discrimination. 

The Battle of Algiers displays several of the themes we discussed this year. There are multiple explanations as to why the Algerians gained a sense of nationalism and how that nationalism grew over time as they were under French colonial rule. The lessons we learned in class helped me recognize these theories throughout the movie and apply them to events that occurred during the Battle of Algiers. 
