---
title: "news article"
format: html
editor: visual
---

## Covid-19 and George Washington's Vex System

Many students on the George Washington campus have expressed their annoyance with the college's bus system. GW has two campuses, one placed on Foggy Bottom and the other on Mount Vernon, and the school provides transportation between the two for students to get to classes, sports activities, and dorms through a system of buses called Vexes. It's difficult for students to walk or bike between the two because of their distance leaving students to rely on the vexes. As of lately, the vexes have been running slower, leaving students late to classes or waiting to get back to their dorms for upwards of forty minutes. Many in desperate attempts to get to class will call an uber to the Mount Vernon location in hopes of getting there on time for their class. Students have commented on the issue such as GW student Margaret Rabbitt, "It's annoying because I have practice in the morning and when the vex doesn't show up I'm late. I even get on a super early one sometimes and I'm still just barely making it." Another student named Haley Curtis discussed how she has been at GW for three years and the vexes have never been this slow before. Curtis talked about how freshman year the Vexes were at the stop every 5 minutes and there wasn't a time you couldn't catch one. This has left students like Curtis and Rabbitt wondering what is happening with the Vex system. Curtis commented, "Why make us go to classes on the Vern if they can't provide us with transportation?" Even the people who work at the Vex station are shocked by the lack of buses. Vex workers explained the issue and it shows that the lack of buses goes deeper than poorly planned transportation. One of the Vex workers commented, "With the pandemic happening people aren't showing up to work, we have no one to work the buses." With the ongoing spread of Covid-19, it has left many bus drivers out of a job or unable to show up to drive. With the university already putting in many Covid-19 regulations such as masks in buildings and on the vexes, the question remains of what will be done about the vex system and how does the university plan to fix it? The situation has since tried to be fixed with the use of larger buses. Before, vexes could only fit upwards of maybe twenty-five people, but the new buses that have been added into the rotation take up to around sixty people. The issue still remains that you can have a bigger bus, but what are you going to do if you have no one to drive it? 
